### ISSUE TITLE
新功能想法建议

### ISSUE THREAD

**Issue by mqdlf995** [hacker-frok/LiteLoaderQQNT-Plugin-Brevity-btn#1]
是否可以将现在的隐藏侧边栏按钮修改成设置（调用qqnt本身的设置），或者增加一个设置按钮在隐藏侧边栏的这个位置（如果可以添加一个或多个可以自选QQNT自带功能的按钮更好）

**Comment by hacker-frok** [comment]
目前暂没想到有什么办法可以调用内置的功能来打开内置的窗口、界面，可能后面会找到方法吧.
