### ISSUE TITLE
MacOS 下插件没有效果

### ISSUE THREAD

**Issue by MarchPhantasia** [hacker-frok/LiteLoaderQQNT-Plugin-Brevity-btn#6]
rt，macos 下插件没有起作用
<img width="1203" alt="image" src="https://github.com/hacker-frok/LiteLoaderQQNT-Plugin-Brevity-btn/assets/161869772/a8894c93-7e71-4e65-98c2-e682b21aa4cd">

**Comment by Skyearn** [comment]
是有的，注意窗口右上角有一个小小的箭头，点下去。

**Comment by MarchPhantasia** [comment]
I have received your email.Thank you for your email.
