### ISSUE TITLE
最新版QQ头像错位显示

### ISSUE THREAD

**Issue by Followtoshe** [hacker-frok/LiteLoaderQQNT-Plugin-Brevity-btn#9]
QQ版本号是：9.9.12-25765
麻烦大佬您能抽空改一下。
![image](https://github.com/user-attachments/assets/97023a4e-819f-4adf-8d59-76d99e1b366f)

**Comment by immortal521** [comment]
插件的renderer.js文件里有个customCssCode变量，字符串里加上
.sidebar__upper .qq-logo {
  display: none;
}
可以临时解决一下，后面就等更新吧

**Comment by Error1015** [comment]
![Clip_2024-07-20_23-56-06](https://github.com/user-attachments/assets/9f3ab23d-15d2-405c-a8cb-8fdc5f0a3dbf)
我也是 QQ版本号不知道哪里看的 是现在的最新版本 头像图标覆盖了聊天头像位置

**Comment by hacker-frok** [comment]
> 插件的renderer.js文件里有个customCssCode变量，字符串里加上 .sidebar__upper .qq-logo { display: none; } 可以临时解决一下，后面就等更新吧

有能力的，可以提個pr的

**Comment by hacker-frok** [comment]
已修复
